export const handTypes = {
    PAIR: 'PAIR',
    TWO_PAIRS: 'TWO_PAIRS',
    TRIPS: 'TRIPS',
    STRAIGHT: 'STRAIGHT',
    FLUSH: 'FLUSH',
    FULL_HOUSE: 'FULL_HOUSE',
    QUADS: 'QUADS',
    STRAIGHT_FLUSH: 'STRAIGHT_FLUSH',
    ROYAL_FLUSH: 'ROYAL_FLUSH'
}
